### ISSUE TITLE
Option class: BigDecimalNanDeserializer needed for volatility + theoreticalOptionValue

### ISSUE THREAD

**Issue by Somanko** [studerw/td-ameritrade-client#31] opened 2020-10-18 10:00 UTC
Getting Exception as these 2 returns NaN for MSFT getOptionChain

**Comment by higgsja** [comment] 2020-10-18 22:36
Having this issue on option chains. Tracked it down to 
`DefaultMapper
	public static <T> T fromJson(InputStream in, TypeReference<T> typeReference) {
    try (BufferedInputStream ignored = new BufferedInputStream(in)) {
      return defaultMapper.readValue(in, typeReference);
    } catch (IOException e) {
      throw new RuntimeException(e);
    }`
with an exception like:
`Cannot deserialize value of type `java.math.BigDecimal` from String "NaN": not a valid representation at [Source: (BufferedInputStream); line: 1, column: 38443] (through reference chain: com.studerw.tda.model.option.OptionChain["putExpDateMap"]->java.util.LinkedHashMap["2020-10-23:5"]->java.util.LinkedHashMap["42.0"]->java.util.ArrayList[0]`

Apparently some field on the return is not a number but I am not smart enough to track further. I've tried a couple tickers, same result.

I'll also post this under #31.

**Comment by studerw** [comment] 2020-10-18 22:38
I know how to fix that. Give me a few hours to take a look...

**Comment by higgsja** [comment] 2020-10-18 23:06
Thanks!!

**Comment by studerw** [comment] 2020-10-19 20:03
@higgsja what version are you using? The latest build or the last release 2.2.0?

**Comment by higgsja** [comment] 2020-10-20 11:19
2.2.0

If you cannot recreate this issue let me know. Could be I have another incorrect version of some jar file.

**Comment by higgsja** [comment] 2020-10-20 16:37
Went ahead and looked through the jar versions. Seems ok. Let me know if you discover the issue on this or if I can help further.

**Comment by studerw** [comment] 2020-10-20 20:45
Can you build the master branch and then trying using 2.3.0-SNAPSHOT in your project? The fix to your issue is in one of the last few commits.

**Comment by higgsja** [comment] 2020-10-20 21:04
I can try ...

**Comment by higgsja** [comment] 2020-10-20 21:56
Ok, that works in a limited way:
Huge number of 'WARN com.studerw.tda.parse.BigDecimalNanDeserializer - volatility using invalid NAN instead of a valid double' for the various elements including the greeks, etc. Could be tdAmeritrade does not actually provide those elements?

However, it does not fail and the basic info is now available.

Thanks!!!

**Comment by studerw** [comment] 2020-10-20 22:00
Yeah I think the problem is that TDAs internal API is in Java, and a lot of these doubles are too close to zero for JavaScript to represent so the JS converts to NAN. So we lose precision but there isn’t any good way to solve it on our end. TDA would need to use a better library for representing very small floating point numbers without truncating them to NAN.

**Comment by higgsja** [comment] 2020-10-20 22:25
harrumph.

I sent a message to the tdAmeritrade team last May. They answered (not a useful answer) yesterday. Clearly not a priority ...

**Comment by studerw** [comment] 2020-10-21 23:48
@higgsja, I made and published new release 2.3.0 if you want the fixes for NAN. I'm going to close this unless there is something else.

**Closed by studerw** 2020-10-21 23:48 UTC
